[package]
name = "Mokopack"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "main"
path = "rs-wasm/src/main.rs"
[lib]
name = "lib"
path = "rs-wasm/src/lib.rs"
crate-type = ["cdylib","rlib"]
[dependencies]
wasm-bindgen = "0.2"
openssl = { version = "0.10", features = ["vendored"] }
